### PR TITLE
fix: add DatePicker support for custom Date/Datetime fields in UniInput

### LINKED ISSUE #2669: Custom Date Field Doesn’t Show DatePicker on New Ticket Form
### Information about bug

https://github.com/user-attachments/assets/328c34a0-c9e8-481a-874e-12388297f414

**Description:**
Added a custom field `due_date` with FieldType **Date** and added it to the **HD Ticket Template**.
When creating a new ticket, the field shows as a plain text input instead of a DatePicker.

**Expected:**
`due_date` should render as a DatePicker to allow easy date selection.

**Actual:**
Field renders as a text input, requiring users to manually type the date.

**Steps to Reproduce:**

1. Create custom field `due_date` with type = Date
2. Add it to HD Ticket Template Fields
3. Open “Create New Ticket” form

**Result:**
No DatePicker displayed for the field.

--

### Version

Frappe Helpdesk Latest Version

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell

```

### PR DESCRIPTION
**Pull request by samarth93**
Fixes #2669

Custom Date and Datetime fields on the new ticket form were rendering as plain text inputs instead of proper DatePicker/DateTimePicker components.

Changes:
- Import DatePicker and DateTimePicker from frappe-ui
- Add handling for 'Date' fieldtype to render DatePicker component
- Add handling for 'Datetime' fieldtype to render DateTimePicker component
- Add date formatting in transValue for proper display

### CODE REVIEW

**Comment by KerollesFathy** [comment]
> @KerollesFathy Yes, this PR fixes both #2669 and #2670 since #2670 is a tracking issue for #2669.
> 
> The fix adds DatePicker and DateTimePicker support to the UniInput component, which is used in the new ticket form for custom fields. This resolves the issue where Date and Datetime fields were rendering as plain text inputs.
> 
> Changes made:
> 
> * Date fields now render with DatePicker
> * Datetime fields now render with DateTimePicker.
> * Proper date formatting for display
> 
> Both issues should be resolved with this PR

Ok, I will close the PR 👍🏼

File: desk/src/components/UniInput.vue [hunk 1]
```diff
@@ -27,7 +27,8 @@
 import { Autocomplete, Link } from "@/components";
 import { APIOptions, Field } from "@/types";
 import { parseApiOptions } from "@/utils";
-import { createResource, FormControl } from "frappe-ui";
+import { createResource, DateTimePicker, dayjs, FormControl } from "frappe-ui";
+import DatePicker from "frappe-ui/src/components/DatePicker/DatePicker.vue";
```
Comment (RitvikSardana) [inline desk/src/components/UniInput.vue]: import from frappe-ui not like this
